"""empty message

Revision ID: 233d4be272d2
Revises: ea127c51578e
Create Date: 2024-05-24 12:50:52.018029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233d4be272d2'
down_revision = 'ea127c51578e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
