"""empty message

Revision ID: d17305fb8d9b
Revises: 5d8f9612bbc5
Create Date: 2024-05-10 13:16:23.511053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17305fb8d9b'
down_revision = '5d8f9612bbc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gb', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('gb')

    # ### end Alembic commands ###
