"""empty message

Revision ID: da5be0407a60
Revises: a5e4e3f4a99a
Create Date: 2024-06-24 17:59:33.745354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5be0407a60'
down_revision = 'a5e4e3f4a99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_cart', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('description_cart', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('count_cart', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_cart', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gb_cart', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('gb1_cart', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('start_count_cart', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount_cart', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count1_cart', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_cart', sa.String(length=60), nullable=True))
        batch_op.drop_column('start_count')
        batch_op.drop_column('discount')
        batch_op.drop_column('name')
        batch_op.drop_column('count')
        batch_op.drop_column('gb1')
        batch_op.drop_column('price')
        batch_op.drop_column('count1')
        batch_op.drop_column('gb')
        batch_op.drop_column('description')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('gb', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('count1', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('gb1', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('start_count', sa.INTEGER(), nullable=True))
        batch_op.drop_column('user_cart')
        batch_op.drop_column('count1_cart')
        batch_op.drop_column('discount_cart')
        batch_op.drop_column('start_count_cart')
        batch_op.drop_column('gb1_cart')
        batch_op.drop_column('gb_cart')
        batch_op.drop_column('price_cart')
        batch_op.drop_column('count_cart')
        batch_op.drop_column('description_cart')
        batch_op.drop_column('name_cart')

    # ### end Alembic commands ###
